language: python

python:
    - "2.7"

env:
    - DB=mysql

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential python-dev python-pip python-virtualenv python-imaging python-lxml python-pyquery libxml2-dev libxslt-dev libjpeg8 libjpeg62-dev libfreetype6 libfreetype6-dev zlib1g-dev python-bcrypt sqlite3
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib
    - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib

install:
    - pip install -r badger/requirements/tests.txt --use-mirrors

script: python manage.py test -v2 badger

notifications:
    email:
        - me@lmorchard.com
